### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by JoelFilho** [JoelFilho/TDP#1]
Implement CI workflows with GitHub Actions

### Platforms

- Windows
- Linux
- Mac

### Tasks

- [ ] Compile and run examples
- [ ] Compile and run tests (CTest)
- [ ] Run static analysis
- [ ] Integrate sanitizers for tests and examples

**Comment by JoelFilho** [comment]
Re-adding this to the v1.0 milestone, because Address, Thread and UB sanitizer are very important in this application.

(Especially since there's already UB in the queue implementation)

**Comment by XIE-Yao** [comment]
Clap!  This project is alive again!  Are you intend to make TDP  an alternative of  intel TBB's pipeline module ?

**Comment by JoelFilho** [comment]
Hello @XIE-Yao! 

I can't guarantee the project is _alive_ like in the initial development, as life comes in the way, and we end up prioritizing other stuff... It's been in maintenance mode, only fixing new issues, without implementing the new ones I wanted to do.

But what features would you like to see from the TBB pipeline module? Except for the `max_number_of_live_tokens`, I can't see anything else that TDP doesn't already do!

(If you would like a specific feature, you can open an issue and we'll discuss that)
